steps:
  - id: Build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --no-cache
      - -t
      - us-east1-docker.pkg.dev/olami-services/cloud-run-source-deploy/$REPO_NAME/souled-retention-dashboard:$COMMIT_SHA
      - .
      - -f
      - Dockerfile
  - id: Push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - us-east1-docker.pkg.dev/olami-services/cloud-run-source-deploy/$REPO_NAME/souled-retention-dashboard:$COMMIT_SHA
  - id: Deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - souled-retention-dashboard
      - --platform=managed
      - --image=us-east1-docker.pkg.dev/olami-services/cloud-run-source-deploy/$REPO_NAME/souled-retention-dashboard:$COMMIT_SHA
      - --region=us-east1
      - --quiet
images:
  - us-east1-docker.pkg.dev/olami-services/cloud-run-source-deploy/$REPO_NAME/souled-retention-dashboard:$COMMIT_SHA
options:
  logging: CLOUD_LOGGING_ONLY
